name: Generate Snake

on:
  schedule:
    # Executa diariamente à meia-noite
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run the snake generator script
        uses: Platane/snk@v2
        with:
          github_token: ${{ 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 }}
          output: dist/github-contribution-grid-snake.svg

      - name: Push the snake grid to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ 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 }}
